#!/usr/bin/env node

var program = require('commander');
var fs = require('fs');
var path = require('path');

var compile  = require('./compile'),
    serve    = require('./serve'),
    render    = require('./render'),
    generate = require('./generate/generate'),
    utils = require('./utils');

program
  .command('compile [project]')
  .description('Compile the nin project')
  .option('--no-png-compression', 'Do not use the .png.html compression trick')
  .action(function(project, options){
    project = path.resolve(process.cwd(), project || '');
    console.log(options);
    console.log('compiling project');
    compile.compile(utils.findProjectRootOrExit(project), {
        pngCompress: options.pngCompression
    });
  });

program
  .command('run [project]')
  .description('Run the backend project')
  .action(function(project) {
    project = path.resolve(process.cwd(), project || '');
    serve.serve(utils.findProjectRootOrExit(project));
  });

program
  .command('headless [project]')
  .description('Run the backend project headlessly')
  .action(function(project) {
    project = path.resolve(process.cwd(), project || '');
    var shouldRunHeadlessly = true;
    serve.serve(utils.findProjectRootOrExit(project), shouldRunHeadlessly);
  });

program
  .command('render [project]')
  .description('Render recorded pngs to a video file')
  .action(function(project) {
    project = path.resolve(process.cwd(), project || '');
    render.render(utils.findProjectRootOrExit(project));
  });

program
  .command('generate [resource] [name]')
  .description('Generate resources')
  .action(function(resource, name) {
    var projectRoot = utils.findProjectRootOrExit(process.cwd());
    generate.generate(projectRoot, resource, name);
  });

program.parse(process.argv);

if(!process.argv.slice(2).length) {
    program.outputHelp();
}
