#!/usr/bin/env node

var program = require('commander');
var fs = require('fs');
var path = require('path');

var compile  = require('./compile'),
    serve    = require('./serve'),
    render    = require('./render'),
    generate = require('./generate/generate'),
    utils = require('./utils');

program.Command.prototype._outputHelp = program.Command.prototype.outputHelp;
program.Command.prototype.outputHelp = function() {
    this._outputHelp(utils.colorizeCommanderHelpText);
};

program
  .command('compile')
  .description('Compile the nin project')
  .option('--no-png-compression', 'Do not use the .png.html compression trick')
  .action(function(options){
    compile.compile(utils.findProjectRootOrExit(process.cwd()), {
        pngCompress: options.pngCompression
    });
  });

program
  .command('run')
  .description('Run the backend project')
  .action(function() {
    serve.serve(utils.findProjectRootOrExit(process.cwd()));
  });

program
  .command('headless')
  .description('Run the backend project headlessly')
  .action(function() {
    var shouldRunHeadlessly = true;
    serve.serve(utils.findProjectRootOrExit(process.cwd()), shouldRunHeadlessly);
  });

program
  .command('render')
  .description('Render recorded pngs to a video file')
  .action(function(project) {
    render.render(utils.findProjectRootOrExit(process.cwd()));
  });

program
  .command('generate [resource] [name]')
  .description('Generate resources')
  .action(function(resource, name) {
    var projectRoot = utils.findProjectRootOrExit(process.cwd());
    generate.generate(projectRoot, resource, name);
  });

program.parse(process.argv);

if(!process.argv.slice(2).length) {
  program.outputHelp();
}
