#!/usr/bin/env node

var program = require('commander');
var fs = require('fs');

var compile = require('./compile').compile,
    serve   = require('./serve'),
    sg = require('./shadergen');

program
  .version('0.0.1')
  .option('compile', 'Compile the nin project')
  .option('run', 'Run the backend project')
  .parse(process.argv);


(function main () {
  sg.shaderGen(function() {
    console.log('Shader compiled, continuing');
    if(program.compile) {
      console.log('compiling...');
      compile(function(compiled){
        fs.writeFileSync('test-project/bin/test-project.png.html', compiled);
        console.log('compiling complete!');
      });
    } else if(program.run){
      serve.serve();
    } else {
      serve.serve();
    }
  });
})();
